USE pokedex;
CREATE TABLE POKEMON_ATTACK(
id_pokemon INT NOT NULL,
id_attack INT NOT NULL,
pokemon_attack_level int NOT NULL,
CONSTRAINT FK_POKEMON_ATTACK FOREIGN KEY (id_pokemon) REFERENCES POKEMON(id_pokemon),
CONSTRAINT FK_ATTACK_POKEMON FOREIGN KEY (id_attack) REFERENCES ATTACK(id_attack)
)